[package]
name = "uefi-example"
version = "0.1.0"
authors = ["Adam Schwalm <adamschwalm@gmail.com>"]
edition = "2018"

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang/compiler-builtins"
tag = "0.1.23"
features = ["mem"]